@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed May 27 08:20:19 +0300 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 8e8398e5e2d2417e822425089208484d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot modul_Testare_behav xil_defaultlib.modul_Testare -log elaborate.log"
call xelab  -wto 8e8398e5e2d2417e822425089208484d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot modul_Testare_behav xil_defaultlib.modul_Testare -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
